import json
import numpy as np
import streamlit as st
from PIL import Image
import tensorflow as tf
from tensorflow import keras

st.set_page_config(page_title="Vitiligo vs Unknown Classifier", page_icon="\U0001FA79", layout="centered")

MODEL_PATH = "vitiligo_classifier.keras"
CLASS_NAMES_PATH = "class_names.json"
IMG_SIZE = (224, 224)


@st.cache_resource
def load_model():
    model = keras.models.load_model(MODEL_PATH)
    with open(CLASS_NAMES_PATH) as f:
        class_names = json.load(f)
    return model, class_names


def preprocess(image: Image.Image):
    image = image.convert("RGB").resize(IMG_SIZE)
    arr = keras.utils.img_to_array(image)
    arr = np.expand_dims(arr, axis=0)
    return arr  # preprocess_input is baked into the saved model


st.title("Vitiligo vs Unknown Skin Image Classifier")
st.caption(
    "GET 324 — Laboratory Exercise 10 (Mini-Project). "
    "Educational demo only — NOT a medical diagnostic tool."
)

with st.sidebar:
    st.header("About")
    st.write(
        "This app uses a MobileNetV2 transfer-learning CNN trained on real "
        "dermatology images to distinguish **Vitiligo** skin patches from "
        "**Unknown** (non-vitiligo) skin images."
    )
    st.write("Upload a clear, well-lit close-up image of the skin area.")

model, class_names = load_model()

uploaded_file = st.file_uploader("Upload a skin image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded image", use_container_width=True)

    with st.spinner("Analyzing image..."):
        x = preprocess(image)
        prob_positive_class = float(model.predict(x, verbose=0)[0][0])
        # class_names is alphabetically ordered by Keras: ['Unknown', 'Vitiligo']
        vitiligo_index = class_names.index("Vitiligo")
        prob_vitiligo = prob_positive_class if vitiligo_index == 1 else 1 - prob_positive_class
        predicted_label = "Vitiligo" if prob_vitiligo >= 0.5 else "Unknown"
        confidence = prob_vitiligo if predicted_label == "Vitiligo" else 1 - prob_vitiligo

    st.subheader(f"Prediction: **{predicted_label}**")
    st.metric("Confidence", f"{confidence * 100:.1f}%")
    st.progress(min(max(confidence, 0.0), 1.0))

    st.write("### Class probabilities")
    st.bar_chart({"Vitiligo": prob_vitiligo, "Unknown": 1 - prob_vitiligo})

    st.warning(
        "This prediction is generated by a course mini-project model and is "
        "**not** a substitute for professional dermatological diagnosis."
    )
else:
    st.info("Upload an image above to get a prediction.")
